Resources:
  LambdaServiceRoleA8ED4D3B:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: AwsTextsStack/Lambda/ServiceRole/Resource
  LambdaD247545B:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters976039a276ac852ed72c853d9ec962c3d25ef9c4e700c637ecec58686e2d4887S3Bucket9AD7F376
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters976039a276ac852ed72c853d9ec962c3d25ef9c4e700c637ecec58686e2d4887S3VersionKeyAD6DC366
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters976039a276ac852ed72c853d9ec962c3d25ef9c4e700c637ecec58686e2d4887S3VersionKeyAD6DC366
      Role:
        Fn::GetAtt:
          - LambdaServiceRoleA8ED4D3B
          - Arn
      Handler: oi.handler
      Runtime: nodejs14.x
    DependsOn:
      - LambdaServiceRoleA8ED4D3B
    Metadata:
      aws:cdk:path: AwsTextsStack/Lambda/Resource
      aws:asset:path: asset.976039a276ac852ed72c853d9ec962c3d25ef9c4e700c637ecec58686e2d4887
      aws:asset:property: Code
  TextEventBus50F77630:
    Type: AWS::Events::EventBus
    Properties:
      Name: TextEventBus
    Metadata:
      aws:cdk:path: AwsTextsStack/TextEventBus/Resource
  LambdaProcessorRuleC28EF8EB:
    Type: AWS::Events::Rule
    Properties:
      EventBusName:
        Ref: TextEventBus50F77630
      EventPattern:
        source:
          - apigateway
        detail-type:
          - text
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - LambdaD247545B
              - Arn
          Id: Target0
    Metadata:
      aws:cdk:path: AwsTextsStack/LambdaProcessorRule/Resource
  LambdaProcessorRuleAllowEventRuleAwsTextsStackLambdaDD197A4BEE0B0869:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - LambdaD247545B
          - Arn
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - LambdaProcessorRuleC28EF8EB
          - Arn
    Metadata:
      aws:cdk:path: AwsTextsStack/LambdaProcessorRule/AllowEventRuleAwsTextsStackLambdaDD197A4B
  ApiGatewayEventBusRole78CD632E:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      Policies:
        - PolicyDocument:
            Statement:
              - Action: events:PutEvents
                Effect: Allow
                Resource:
                  Fn::GetAtt:
                    - TextEventBus50F77630
                    - Arn
            Version: "2012-10-17"
          PolicyName: putEvents
    Metadata:
      aws:cdk:path: AwsTextsStack/ApiGatewayEventBusRole/Resource
  TextApiGateway437DBC5F:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: TextApiGateway
    Metadata:
      aws:cdk:path: AwsTextsStack/TextApiGateway/Resource
  TextApiGatewayCloudWatchRoleE5030C8C:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: AwsTextsStack/TextApiGateway/CloudWatchRole/Resource
  TextApiGatewayAccount54FA72E1:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - TextApiGatewayCloudWatchRoleE5030C8C
          - Arn
    DependsOn:
      - TextApiGateway437DBC5F
    Metadata:
      aws:cdk:path: AwsTextsStack/TextApiGateway/Account
  TextApiGatewayDeployment754CD196b64dc5e6e5965c5c1e7fcb0c52dd006b:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: TextApiGateway437DBC5F
      Description: Automatically created by the RestApi construct
    DependsOn:
      - TextApiGatewayPOST0201D577
    Metadata:
      aws:cdk:path: AwsTextsStack/TextApiGateway/Deployment/Resource
  TextApiGatewayDeploymentStagedev47E27826:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: TextApiGateway437DBC5F
      DeploymentId:
        Ref: TextApiGatewayDeployment754CD196b64dc5e6e5965c5c1e7fcb0c52dd006b
      StageName: dev
    Metadata:
      aws:cdk:path: AwsTextsStack/TextApiGateway/DeploymentStage.dev/Resource
  TextApiGatewayPOST0201D577:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId:
        Fn::GetAtt:
          - TextApiGateway437DBC5F
          - RootResourceId
      RestApiId:
        Ref: TextApiGateway437DBC5F
      AuthorizationType: NONE
      Integration:
        Credentials:
          Fn::GetAtt:
            - ApiGatewayEventBusRole78CD632E
            - Arn
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - ResponseTemplates:
              application/json: ""
            StatusCode: "200"
          - ResponseTemplates:
              application/json: "{\"state\":\"error\",\"message\":\"$util.escapeJavaScript($input.path('$.errorMessage'))\"}"
            StatusCode: "400"
        RequestParameters:
          integration.request.header.X-Amz-Target: "'AWSEvents.PutEvents'"
          integration.request.header.Content-Type: "'application/x-amz-json-1.1'"
        RequestTemplates:
          application/json:
            Fn::Join:
              - ""
              - - |-
                  {"Entries": [
                            {"Source": "apigateway", 
                            "Detail": "$util.escapeJavaScript($input.body)", 
                            "DetailType": "text", 
                            "EventBusName": "
                - Ref: TextEventBus50F77630
                - '"}]}'
        Type: AWS
        Uri: arn:aws:apigateway:us-east-1:events:path//
      MethodResponses:
        - StatusCode: "200"
        - StatusCode: "400"
    Metadata:
      aws:cdk:path: AwsTextsStack/TextApiGateway/Default/POST/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/02Qz1LDIBDGn6V3Qo314NGk6s2xE59gJWukCZBhoZ0Ok3eXJa3T0/7237cf1LLePcqHzQucqVL9uE3KeZTpK4AaRUOEIeOg7SD2zlLwUQWx/7EH8GAwoOfkM4Y5lnKH5KJXyJznex20s4tg8TSB+e5BpvdoFZd55p4P6I0mKgsajEydm4oQx0XQrgK2Q7K4yrlsoxoxtEAo8IQ2t9IbxzYS7/1zF69CkYVg1gMEPMMln0AKzayv1m/YKOWiDeIV58ldTFbh6l3GX1IUV7i9ujj5wPDrem6utCyLsK5HeaTtqX6S9bOsN0fSuvL5hjYouzX+ATPDMzeLAQAA
    Metadata:
      aws:cdk:path: AwsTextsStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters976039a276ac852ed72c853d9ec962c3d25ef9c4e700c637ecec58686e2d4887S3Bucket9AD7F376:
    Type: String
    Description: S3 bucket for asset "976039a276ac852ed72c853d9ec962c3d25ef9c4e700c637ecec58686e2d4887"
  AssetParameters976039a276ac852ed72c853d9ec962c3d25ef9c4e700c637ecec58686e2d4887S3VersionKeyAD6DC366:
    Type: String
    Description: S3 key for asset version "976039a276ac852ed72c853d9ec962c3d25ef9c4e700c637ecec58686e2d4887"
  AssetParameters976039a276ac852ed72c853d9ec962c3d25ef9c4e700c637ecec58686e2d4887ArtifactHashE99591F9:
    Type: String
    Description: Artifact hash for asset "976039a276ac852ed72c853d9ec962c3d25ef9c4e700c637ecec58686e2d4887"
Outputs:
  TextApiGatewayEndpoint1B713D84:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: TextApiGateway437DBC5F
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: TextApiGatewayDeploymentStagedev47E27826
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

